version: '3.3'

services:
    db:
      restart: always
      image: mysql:5.7
      ports:
        - 1234:3306
      environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
      volumes:
        - dbdata:/var/lib/mysql
volumes:
    dbdata:
